---
# tasks file for disable-ipv6

- name: Blacklist IPv6 LKM
  kernel_blacklist:
    name: ipv6
    state: present


- name: Disable IPv6 in grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*ipv6.disable=1)\"[^\"]+)(\".*)'
    line: '\1 ipv6.disable=1\2'
  register: grub_cfg

- name: Update grub config
  command: "/usr/sbin/grub2-mkconfig -o {{ grub_config_item }}"
  with_items:
    - /boot/grub2/grub.cfg
    - /boot/efi/EFI/centos/grub.cfg
  when: grub_cfg.changed
  loop_control:
    loop_var: grub_config_item
