---
# tasks file for disable-ipv6

- name: Blacklist IPv6 LKM
  kernel_blacklist:
    name: ipv6
    state: present


- name: Disable IPv6 in grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*ipv6.disable=1)\"[^\"]+)(\".*)'
    line: '\1 ipv6.disable=1\2'
  register: grub_cfg

- name: Update grub config
  command: "/usr/sbin/grub2-mkconfig -o {{ grub_config_item }}"
  with_items:
    - /boot/grub2/grub.cfg
    - /boot/efi/EFI/centos/grub.cfg
  when: grub_cfg.changed
  loop_control:
    loop_var: grub_config_item


- name: ipv6 sysctl
  sysctl: name={{ ipv6_sysctl_item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  loop_control:
    loop_var: ipv6_sysctl_item
