---
# tasks file for libvirtd

- name: Install packages
  yum:
    state: present
    name:
      - libvirt
      - qemu-kvm
      - virt-install


- name: Allow KVM to use bridge0
  lineinfile:
    path: /etc/qemu-kvm/bridge.conf
    line: 'allow bridge0'
    create: yes


- name: Create /etc/kickstarts
  file:
    path: /etc/kickstarts
    state: directory


- name: Generate Kickstarts
  template:
    dest: "/etc/kickstarts/{{ ks_item.key }}.cfg"
    src: kickstart.j2
  with_dict: "{{ hostvars }}"
  no_log: yes
  loop_control:
    loop_var: ks_item


- name: virt-install commands
  template:
    src: vminstall.j2
    dest: "/usr/local/bin/vminstall"
    mode: 0755
  register: vm_config
  vars:
    vm_items:
    - k3s-master01
    - k3s-node01
    - k3s-node02
    - k3s-node03
  loop_control:
    loop_var: vm_items

- name: Start VM
  shell: /usr/local/bin/vminstall
  when: vm_config.changed
