---
# tasks file for libvirtd

- name: Install packages
  yum:
    state: present
    name:
      - libvirt
      - qemu-kvm
      - virt-install


- name: Allow KVM to use bridge0
  lineinfile:
    path: /etc/qemu-kvm/bridge.conf
    line: 'allow bridge0'
    create: yes


- name: Create /etc/kickstarts
  file:
    path: /etc/kickstarts
    state: directory


- name: Generate Kickstarts
  template:
    dest: "/etc/kickstarts/{{ ks_item.key }}.cfg"
    src: kickstart.j2
  with_dict: "{{ hostvars }}"
  no_log: yes
  loop_control:
    loop_var: ks_item


- name: virt-install commands
  debug:
    msg: "virt-install --name {{ vm_item }} --ram 4096 --disk size=10 --quiet --noautoconsole --autostart --virt-type kvm --wait=-1 --vcpus 1 --os-type linux --os-variant rhel7.7 --network bridge=bridge0 --graphics none --initrd-inject /etc/kickstarts/{{ vm_item }}.cfg --location 'http://mirror.mhd.uk.as44574.net/mirror.centos.org/7.7.1908/os/x86_64/' --extra-args 'console=ttyS0,115200n8 ks=file:/{{ vm_item }}.ks ksdevice=eth0 ip={{ hostvars[vm_item]['ifcfg_ifcfg']['eth0']['ipaddr'] }} nameserver={{ hostvars[vm_item]['ifcfg_ifcfg']['eth0']['dns1'] }} netmask={{ hostvars[vm_item]['ifcfg_ifcfg']['eth0']['mask'] }} gateway={{ hostvars[vm_item]['routes_default'] }}"
  with_items:
    - k3s-node03
  loop_control:
    loop_var: vm_item
