---
# tasks file for routes

- name: Ensure directory is there
  file:
    path: /etc/sysconfig/network-scripts/
    state: directory


- name: Add default gateway
  lineinfile:
    path: /etc/sysconfig/network
    regexp: '^GATEWAY='
    line: "GATEWAY={{ routes_default }}"
    create: yes
  when: routes_default is defined


- name: Generating routes files
  template:
    src: routes.j2
    dest: "/etc/sysconfig/network-scripts/routes-{{ routes_item.key }}"
  with_dict: "{{ routes_routes }}"
  loop_control:
    loop_var: routes_item
