---
# tasks file for base

- name: Install packages
  yum:
    state: present
    name:
      - genisoimage
      - git
      - mkisofs
      - perl
      - syslinux
      - vim
      - wget


- name: Blacklist IPv6 LKM
  kernel_blacklist:
    name: ipv6
    state: present


- name: Disable IPv6 in grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*ipv6.disable=1)\"[^\"]+)(\".*)'
    line: '\1 ipv6.disable=1\2'
# need to run grub2-mkconfig


- name: Disable SELinux
  selinux:
    state: disabled


- name: wheel NOPASSWD
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
