---
# tasks file for base

- name: Install packages
  yum:
    state: present
    name:
      - genisoimage
      - git
      - mkisofs
      - perl
      - syslinux
      - vim
      - wget


- name: Disable SELinux
  selinux:
    state: disabled


- name: wheel NOPASSWD
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
